**NUMPY Exercise** 

In [1]:
from __future__ import print_function
import numpy as np

##  Create Arrays

In [2]:
list1 = [1, 2, 3, 4, 5]       # 1-dimensional list1 is defined
array1 = np.array(list1)      #list1 is converted to an array
array1  

array([1, 2, 3, 4, 5])

In [3]:
  
list2 = [range(1,5), range(6,10)]   #2-dimensional list2 is defined.
array2 = np.array(list2)            #list2 is converted to an array
array2

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [4]:
array2.tolist()

[[1, 2, 3, 4], [6, 7, 8, 9]]

In [5]:
np.zeros(10) #defined new array filled zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
zero_arr = np.zeros((3,6)) #zeros array 3x6 
zero_arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones(10) #ones array 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.linspace(0,10,3) # 5 points between 0 and 1 (0-1 included)

array([ 0.,  5., 10.])

In [9]:
np.logspace(0, 3, 10) # between 10^0 and 10^3, evenly 10 points

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [10]:
range_array = np.arange(9) # array 0-9
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
range_array.astype(float) #copy of the array, cast to specified data type

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

##  Examining Array

In [12]:
array1.dtype # returns type of array

dtype('int64')

In [13]:
array2.ndim # returns dimension of array

2

In [14]:
zero_arr.shape # returns shape of array 3-> rows, 6-> columns

(3, 6)

In [15]:
array2.size # number of elements

8

In [16]:
len(array2) # has 2 elements in first dimension

2

## 4.3 Reshaping

In [17]:
arr3 = np.arange(10, dtype = float).reshape(2, 5) # reshaping the array
print(arr3)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [18]:
arr4 = np.array([0,1,3])
arr4_col = arr4[:, np.newaxis] # used to new axis
print(arr4_col)

[[0]
 [1]
 [3]]


In [19]:
print(arr3.T) # transposing 

[[0. 5.]
 [1. 6.]
 [2. 7.]
 [3. 8.]
 [4. 9.]]


In [20]:
arr3_flt = arr3.flatten() # flat copy of original array
print(arr3)
arr3_flt

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [21]:
arr3_flt = arr3.ravel() # oview of original array 
print(arr3_flt) 

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## 4.4 Stack Array

In [22]:
ln1 = np.array([0,1]) #stacks flat arrays in columns
ln2 = np.array([2,3])
mat = np.stack((ln1, ln2))
print(mat)

[[0 1]
 [2 3]]


# 4.5 Selection

In [23]:
arr  = np.arange(10, dtype=float).reshape((2,5)) 
arr[0] #0th element

array([0., 1., 2., 3., 4.])

In [24]:
arr[0, 3] # 0. row, 3.column -> 3

3.0

In [25]:
arr[0][3] # returns same

3.0

## 4.5.1 Slicing

In [26]:
arr[:, 3] # all index in column 3 

array([3., 8.])

In [27]:
arr[0, :] # all index in row 0

array([0., 1., 2., 3., 4.])

In [28]:
arr[:, :3] # column strictly columns before index 3

array([[0., 1., 2.],
       [5., 6., 7.]])

In [29]:
arr[:, 3:] # columns after 3 included

array([[3., 4.],
       [8., 9.]])

In [30]:
arr[:, 1:4] # column between index 1 and 4 (1 included 4 not)

array([[1., 2., 3.],
       [6., 7., 8.]])

In [31]:
arr[0, ::-1] # column 0 in reverse order

array([4., 3., 2., 1., 0.])

## 4.5.2 Fancy Indexing: Boolean or Integer array indexing

In [32]:
#########################

In [33]:
#Fancy indexing returns a copy not a view
arr2 = arr[:, [1, 2, 3]] # return a copy 1. 2. and 3. coloumns
arr2

array([[1., 2., 3.],
       [6., 7., 8.]])

In [34]:
arr_greater3 = arr[arr>3] # returns elements greater than 5 in arr 
arr_greater3

array([4., 5., 6., 7., 8., 9.])

In [35]:
arr_greater3 [arr_greater3 >5] =0 # elements that re greater than 5 defined 0
arr_greater3

array([4., 5., 0., 0., 0., 0.])

In [36]:
person = np.array(['bob', 'joe', 'will', 'bob'])
person == 'bob' # boolean array is it bob or not

array([ True, False, False,  True])

In [37]:
person[person != 'joe'] # logical selection

array(['bob', 'will', 'bob'], dtype='<U4')

In [38]:
(person == 'Bob') | (person == 'Will')

array([False, False, False, False])

In [39]:
person[person == 'joe'] = 'bob' # assign based on logical selection
print(person)
np.unique(person) # finding unique element of array

['bob' 'bob' 'will' 'bob']


array(['bob', 'will'], dtype='<U4')

# 4.6 Vectorized Operations

In [40]:
num_array = np.arange(6)

In [41]:
num_array * 5 # multiply each element by 5

array([ 0,  5, 10, 15, 20, 25])

In [42]:
num_array = np.sqrt(num_array) # square root of each element
num_array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [43]:
np.ceil(num_array) # round each element to nearest int

array([0., 1., 2., 2., 2., 3.])

In [44]:
np.isnan(num_array) #checking NaN 

array([False, False, False, False, False, False])

In [45]:
num_array + np.arange(6) # add elements

array([0.        , 2.        , 3.41421356, 4.73205081, 6.        ,
       7.23606798])

In [46]:
np.maximum(num_array, np.array([-3, 4, 5, -6, 8, 10])) # find max elements 

array([ 0.        ,  4.        ,  5.        ,  1.73205081,  8.        ,
       10.        ])

### Compute euclidean distance between 2 vector

In [47]:
vec1 = np.random.randn(10)
vec2 = np.random.randn(10)
distance = np.sqrt(np.sum((vec1 -vec2) **2))
distance

3.2645126794573183

### Math and stats

In [48]:
rnd = np.random.randn(2,3) # assign random values array 1x3
rnd

array([[ 0.74497734, -1.56269687, -2.30782012],
       [ 1.65424447,  1.39308688,  1.33148218]])

In [49]:
rnd.mean() #mean of array

0.20887897844645012

In [50]:
rnd.std() #standard deviation of array

1.5551701135486051

In [51]:
rnd.argmin() # min element index

2

In [52]:
rnd.sum() # sum of all element 

1.2532738706787008

In [53]:
rnd.sum(axis = 0) #sum of coloumns

array([ 2.39922181, -0.16960999, -0.97633794])

In [54]:
rnd.sum(axis = 1) #sum of rows

array([-3.12553965,  4.37881352])

### Methods for boolean arrays

In [55]:
(rnd > 0).sum() # count numbers of positive value

4

In [56]:
(rnd > 0).any() # checks if any value is True

True

In [57]:
(rnd > 0).all() # checks if all values True

False

### Random numbers

In [58]:
np.random.seed(12345)

In [59]:
np.random.rand(2,3) #  

array([[0.92961609, 0.31637555, 0.18391881],
       [0.20456028, 0.56772503, 0.5955447 ]])

# 4.8 Exercises

In [60]:
X = np.random.randn(4,2)
X

array([[ 0.09290788,  0.28174615],
       [ 0.76902257,  1.24643474],
       [ 1.00718936, -1.29622111],
       [ 0.27499163,  0.22891288]])

In [61]:
X.argmin(axis = 1)
X.std()

0.7252074128812068